import ProtectedRoute from "@/components/auth/ProtectedRoute";
import { DynamicSidebar } from "@/components/shared/Sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Auth Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <ProtectedRoute allowedRoles={["user"]}>{children}</ProtectedRoute>;
}
